service: rss
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: dev
  ecr:
    images:
      img:
        path: ./
        platform: linux/amd64

custom:
  stage: ${opt:stage, self:provider.stage}
  product: feed-parser
  # DynamoDB variables
  dynamoDB_name: ${self:service}-${self:custom.product}-${self:custom.stage}-rss-feed-source
  dynamoDB_arn:
    Fn::GetAtt: [RssFeedSourceTable, Arn]
  # Step Function variables
  rss_pipeline_step_function_arn: 
    Fn::GetAtt: [RSSPipeline, Arn]
  rss_pipeline_step_function_name: 
    Fn::GetAtt: [RSSPipeline, Name]

# Lambdas
functions:
  # Invokes Step-Function Pipeline
  invoke-step-function-lambda:
    handler: Lambdas/invoke-step-function-lambda/lambda-invoke-step-function.lambda_handler
    name: ${self:service}-${self:custom.product}-${self:custom.stage}-invoke-stepfunction
    description: Lambda to invoke RSS Step-Function Pipeline
    environment:
      STEP_FUNCTION_ARN: ${self:custom.rss_pipeline_step_function_arn}
    timeout: 20
    events:
      - schedule: rate(24 hours)
    role: LambdaDynamoDBRole
  # Pulls RSS Data
  get-feed-and-article:
    handler: Lambdas/rss-feed-parse-lambda/lambda-get-feed.lambda_handler
    name: ${self:service}-${self:custom.product}-${self:custom.stage}-get-rss-feed
    description: Lambda to pull RSS data
    environment:
      DYNAMODB_TABLE_NAME: ${self:custom.dynamoDB_name}
    package:
      include:
        - Lambdas/rss-feed-parse-lambda/
        - requirements.txt
    timeout: 60
    role: LambdaDynamoDBRole
  # Pull articles with Selenium
  get-artcile-selenium:
    name: ${self:service}-${self:custom.product}-${self:custom.stage}-scrape-article
    description: Lambda wiht Selenium to scrape Article
    environment:
      DYNAMODB_TABLE_NAME: ${self:custom.dynamoDB_name}
    timeout: 900
    memorySize: 2048
    role: LambdaDynamoDBRole
    image:
      name: img

# Plugins
plugins:
  - serverless-python-requirements
  - serverless-step-functions

# Resources
resources:
    - Resources:
    # All the resources
    - ${file(./YAML/dynamodb.yml)}
    - ${file(./YAML/iam.yml)}

stepFunctions:
  stateMachines:
    RSSPipeline:
      id: RSSPipeline
      name: ${self:service}-${self:custom.product}-${self:custom.stage}-pull-and-parse-rssfeeds
      definition:
        Comment: "Step-Function that runs the RSS Pipeline"
        StartAt: GetRSSFeedsData
        States:
          GetRSSFeedsData:
            Type: Task
            Resource:
              Fn::GetAtt: [get-feed-and-article, Arn]
            Next: ScrapeArticleData
          ScrapeArticleData:
            Type: Task
            Resource:
              Fn::GetAtt: [get-artcile-selenium, Arn]
            End: true